export default {
  HOME_SCREEN: 'HOME_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  SIGN_UP_SCREEN: 'SIGN_UP_SCREEN',
  OTP_VERIFY_SCREEN: 'OTP_VERIFY_SCREEN',
  WELCOME_SCREEN: 'WELCOME_SCREEN',
  INTRO_SCREEN: 'INTRO_SCREEN',
};
